apiVersion: apps/v1
kind: Deployment
metadata:
  name: sol-deployment
  labels:
    app: sol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sol
  template:
    metadata:
      labels:
        app: sol
    spec:
      containers:
      - name: sol-container
        image: chimenesjr/solitaire:nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sol-service
spec:
  type: NodePort
  selector:
    app: sol
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000